### PR TITLE
temporary support for xatsopt -d/-s [filename]

### PR DESCRIPTION
**Pull request by sparverius**
This is particularly useful for emacs compile mode

### CODE REVIEW

**Comment by githwxi** [comment]
I took a look. Instead of merging, I generalized process_nil to process_fpath. Eventually, I suggest to design a script language for compiling ATS/Xanadu. In particular, xatsopt command-line can be first translated into this script language.

**Comment by githwxi** [comment]
Richard,

Would you like to take the initiative to implement such a script language for ATS/Xanadu?
We could start a discussion shortly.

**Comment by sparverius** [comment]
Sure, what functionality should it support?

**Comment by githwxi** [comment]
I'll come up with some examples first.

**Pull request closed without merging**
